language: java
os: osx
jdk: openjdk11

cache:
 directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

before_install:
 - chmod +x gradlew
 - wget https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_windows-x64_bin.zip
 - unzip openjdk-11.0.2_windows-x64_bin.zip

install: skip

script: ./gradlew -b build-travis.gradle runtimeZip --warning-mode all

before_cache:
 - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
 - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

before_deploy:
 - git config --local user.name "Thykof"
 - git config --local user.email "thykof@protonmail.ch"
 - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
 - git tag $TRAVIS_TAG

deploy:
  # Upload to s3
  - provider: s3
    access_key_id: $s3id
    secret_access_key: $s3key
    bucket: $s3bucket
    skip_cleanup: true
    region: eu-west-3
    local_dir: build
    glob: *.zip
    on:
      all_branches: true
  #acl: public_read
  #default_text_charset: 'utf-8'  # Default is ''
  # Github release on branch master
  - provider: releases
    token: $token
    file:
     - "build/libs/uPMT.jar"
     - "build/uPMT-osx-x64.zip"
     - "build/uPMT-win-x64.zip"
    on:
      branch: dev
    skip_cleanup: true
